spring.application.name=VIATE
spring.mainClass=com.AVASPP.VIATE.VIATEApplication.java

spring.jpa.database=postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/VIATE
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG

logging.level.com.AVASPP.VIATE.controller=DEBUG

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param