spring.application.name=VIATE
spring.mainClass=com.VIATE.VIATE.VIATEApplication.java

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.database=postgresql